### PR TITLE
The word test in test method is a nono

### PR DESCRIPTION
**Pull request by casz**
consistency is key as discovered in #168 :trollface:

### CODE REVIEW

**Comment by casz** [comment]
:laughing: coveralls your drunk

**Comment by olamy** [comment]
for my curiosity why is it a nono?

**Comment by casz** [comment]
so says reviewer in #168 https://github.com/jenkinsci/jira-plugin/pull/168#discussion_r268453418

**Comment by olamy** [comment]
@casz well why not but it's very cosmetic change :)

**Pull request merged**
