### PR TITLE
[JENKINS-33859] NPE Error updating JIRA issues

### PR DESCRIPTION
**Pull request by alvarolobato**
Added NP check after retrieving the issue from the API.
https://issues.jenkins-ci.org/browse/JENKINS-33859

@reviewbybees

### CODE REVIEW

**Comment by armfergom** [comment]
:bee: LGTM. If it's not too time consuming, it'd be good to have test coverage for it.

**Comment by warden** [comment]
@alvarolobato any chance you can add a simple test for it so we don't decrease coverage?

**Comment by oleg-nenashev** [comment]
:bee: for the implementation, but I agree regarding the test. It should be pretty easy to implement it

**Comment by warden** [comment]
Still waiting for a simple test to not decrease coverage :)

**Comment by alvarolobato** [comment]
Couldn't prepare the test yet. I expect to be able to send it this week.

**Pull request merged**
