### PR TITLE
README update

### PR DESCRIPTION
**Pull request by warden**

### CODE REVIEW

**Comment by warden** [comment]
@olamy since we fixed fixed https://issues.jenkins-ci.org/browse/INFRA-2641 I reenabled required check for *continuous-integration/jenkins/pr-merge*.

**Comment by olamy** [comment]
@warden please remove this because it fail the release!
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project jira: Unable to commit files
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] remote: error: GH006: Protected branch update failed for refs/heads/master.        
[ERROR] remote: error: Required status check "continuous-integration/jenkins/pr-merge" is expected.        
[ERROR] To github.com:jenkinsci/jira-plugin.git
[ERROR]  ! [remote rejected] master -> master (protected branch hook declined)
[ERROR] error: failed to push some refs to 'github.com:jenkinsci/jira-plugin.git'
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

**Comment by warden** [comment]
You have just removed master protection in the settings - please never do that.

**Comment by olamy** [comment]
so how am I supposed to release?? 
we need to make this simple. we are only 2 so we do not need some complicated process

**Comment by warden** [comment]
branch protection for *master* must always be active and it is independent from the build requirement that I enabled recently - it was always there. The current setting that you just as I see reenabled is how it should look like - so it's fine for now 👍 

I'll investigate how to do releases with the build check enabled.

**Comment by olamy** [comment]
ah yes ok.  sorry for the confusion

**Pull request merged**
