### PR TITLE
Bumping java-rest-client version to 5.1.0

### PR DESCRIPTION
**Pull request by madchap**

### CODE REVIEW

**Comment by warden** [comment]
You meant [5.1.0](https://mvnrepository.com/artifact/com.atlassian.jira/jira-rest-java-client-api?repo=atlassian-public) ?

**Comment by madchap** [comment]
Of course, thanks @warden for the 4-eye here..

(btw, was talking to @olamy today, and I noticed the atlassian repository URL may not be accurate anymore.)

**Comment by artkoshelev** [comment]
compilation failure...

**Comment by madchap** [comment]
Yea, this looks like crap. Let's forget about it, as I am not convinced of the value anyways.

**Pull request closed without merging**
