### PR TITLE
[JENKINS-56810] Add current date in startDate when creating new version

### PR DESCRIPTION
**Pull request by mpare**
When creating a new version in Jira through Jenkins we want to set the current date in "Start Date" for Version Reports. Currently we have to manually edit them in Jira after each build in Jenkins.

This field was never added to the Jira Rest Java Client Library even though it is available on the Jira Rest API (undocumented).

If I query a particular version with a "Start Date" already filled in Jira, I can see the field "startDate".

`
{
	"self": "https://.../rest/api/latest/version/21755",
	"id": "21755",
	"name": "CLAP-3.0.2",
	"archived": false,
	"released": false,
	"startDate": "2019-03-14",
	"userStartDate": "March 14, 2019",
	"projectId": 12400
}
`

### CODE REVIEW

**Comment by artkoshelev** [comment]
Please provide extended description and motivation for your changes.

**Comment by mpare** [comment]
Description updated.

**Comment by olamy** [comment]
@mpare can you please create a jira issue to get this in the changelog? thanks

**Comment by mpare** [comment]
Jira issue created : https://issues.jenkins-ci.org/browse/JENKINS-56810

**Comment by olamy** [comment]
@mpare thanks a lot for your work! and your patience :)

**Pull request merged**
