### PR TITLE
JENKINS-48716 Prevent Guava InvalidCacheLoadException

### PR DESCRIPTION
**Pull request by gmshake**
Issue link [JENKINS-48716](https://issues.jenkins-ci.org/browse/JENKINS-48716)

### CODE REVIEW

**Comment by artkoshelev** [comment]
could you please provide test reproducing the problem?

**Comment by gmshake** [comment]
@artkoshelev Do you mean test steps or unit test? There're logs on our production instance like this, and I've made up local build environment and reproduced the problem.
`
Dec 25, 2017 5:45:29 PM WARNING hudson.model.listeners.RunListener report
RunListener failed
com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key PR-178.
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2383)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2351)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4764)
	at hudson.plugins.jira.JiraSite.getIssue(JiraSite.java:467)
	at hudson.plugins.jira.JiraJobAction.setAction(JiraJobAction.java:99)
	at hudson.plugins.jira.JiraJobAction$RunListenerImpl.onStarted(JiraJobAction.java:130)
	at hudson.plugins.jira.JiraJobAction$RunListenerImpl.onStarted(JiraJobAction.java:122)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:240)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:254)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
`

**Comment by artkoshelev** [comment]
@gmshake i mean unit or integration test, so we can validate that your change actually fixes problem and document this new behavior

**Comment by gmshake** [comment]
@artkoshelev Tests added.

**Comment by warden** [comment]
Nice one! 🍺 for this one and for passing 50% coverage :-)

**Comment by gmshake** [comment]
@warden :)

**Pull request merged**
