### PR TITLE
JENKINS-44524 Support configuring a site on a folder

### PR DESCRIPTION
**Pull request by bluesliverx**
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/jira-plugin/124)

### CODE REVIEW

**Comment by artkoshelev** [comment]
Can you please describe your change?

**Comment by bluesliverx** [comment]
The PR adds support for configuring a jira site on a folder in Jenkins instead of using global configuration. This is to support our usage of Jenkins in a multitenant environment where each tenant is granted admin access to a single folder but cannot modify global config. 

Functionally it just injects another check for a jira site from the get method that steps use. If a job doesn't specify the jira site specifically from global config, it will walk up the folder tree until it finds a folder configured with a jira site. If none of the parent folders have jira sites configured, it falls back to the precious behavior of getting it from global config.

**Comment by jmcu** [comment]
This is something we could use. Teams have separate folders and separate JIRA projects so configuration of jira-plugin at the global level doesn't work. What is the status of this pull request, and potential for it to be merged?

**Comment by bluesliverx** [comment]
I just added tests for it to make sure everything is working as expected, and now the build is working.  Not sure what was going on with it before to be honest.

As far as I know, this PR is ready to be merged, just waiting on approval/merging from the code maintainer.  (@warden?)

**Comment by i386** [comment]
This will be useful for us @cyrille-leclerc

**Comment by cyrille-leclerc** [comment]
That's a great improvement, thanks @bluesliverx!

**Comment by bluesliverx** [comment]
Glad others like it :)  Now if we can just get this merged... @artkoshelev, any chance this can be brought in and a new version released?  It is obviously becoming more and more common for large JIRA installations to do this.

**Comment by bluesliverx** [comment]
Great, thanks! Looks like 2.4 was released yesterday - I'll try it out.

**Pull request merged**
