### PR TITLE
Reenable full build on TravisCI

### PR DESCRIPTION
**Pull request by warden**
As JenkinsCI is sometimes failing and to have the parity with it in order not to confuse contributors, reenable normal full build on TravisCI too.
Replaces #223 
Reasons:
https://issues.jenkins-ci.org/browse/INFRA-2569
https://issues.jenkins-ci.org/browse/INFRA-2548
https://issues.jenkins-ci.org/browse/INFRA-2544
https://issues.jenkins-ci.org/browse/INFRA-2393

### CODE REVIEW

**Comment by warden** [comment]
What do you mean by "report" ?
Jenkins infra will (still) be building and publishing the plugin, nothing changes here (see Jenkinsfile).
Travis is (still) going to be an additional build that is getting feedback quicker and providing coverage and SonarCloud results.
Additionally I disabled custom branches on Travis so that only master and PRs are built - for coverage reports.

**Comment by artkoshelev** [comment]
Branch builds are reporting directly to PR as a comment. Where Travis build will publish results from master build? What will happen if it fails?

**Comment by warden** [comment]
Again, there is no change here, Travis build is building master for a long time already.
For master branch, Travis results are visible as badges in the main README.md:
- Coveralls coverage report
- Travis build status (second build status badge)

**Comment by artkoshelev** [comment]
Badges, right... 👍

**Pull request merged**
