### PR TITLE
drop unused and test-only dependencies

### PR DESCRIPTION
**Pull request by t-8ch**
reduces the final artifact size from 4.4 MiB to 3.7 MiB

### CODE REVIEW

**Comment by warden** [comment]
LGTM, thanks!

**Comment by warden** [comment]
Added `breaking-compatibility` as a public class was removed.

**Comment by olamy** [comment]
removing a public class... please make it clear in releases https://github.com/jenkinsci/jira-plugin/releases

**Comment by warden** [comment]
Added info in https://github.com/jenkinsci/jira-plugin/releases/tag/untagged-14892662761f0550eb9f

**Comment by olamy** [comment]
@warden thanks!

**Pull request merged**
