### PR TITLE
[WIP] Option to disable jira annotating the changelogs.

### PR DESCRIPTION
**Pull request by christ66**
@reviewbybees

---
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/jira-plugin/118)

### CODE REVIEW

**Comment by christ66** [comment]
To add some more context to this:

Sometimes when viewing an individual build, or the changeset of a project it might take a very long time because the changeset for one build might be very large. I encountered a performance issue when the build had several hundred in the changeset (was not built in a very long time).

Snippet of thread dump causing issue:

```
at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4764)
at hudson.plugins.jira.JiraSite.getIssue(JiraSite.java:424)
at hudson.plugins.jira.JiraChangeLogAnnotator.annotate(JiraChangeLogAnnotator.java:101)
at hudson.scm.ChangeLogSet$Entry.getMsgAnnotated(ChangeLogSet.java:252)
at sun.reflect.GeneratedMethodAccessor611.invoke(Unknown Source)
```

It might also be that the performance issue I am encountering is because I am hitting the max api calls, which caused some of the queries to hang. From looking at the `JiraSite.getIssue` it looks like that this will make sure that the jira exists, however it could be that there's a rate limit for the number of Rest API calls I can make.

**Comment by warden** [comment]
Do you think it's a good idea to disable it on a "site" level?
This seems like a corner-case to me and I think it might be better to actually disable it in specific project/job rather than on the whole site.

**Comment by stephenc** [comment]
I think it is a good idea to be able to do both: per project and entire site

**Comment by christ66** [comment]
I will update the pr to provide an option for project level as well.

**Comment by warden** [comment]
@christ66 will you have a chance to take a look on this by the end of Jan?

**Comment by warden** [comment]
ping @christ66

**Comment by artkoshelev** [comment]
Can you add test to document new behavior?

**Comment by warden** [comment]
As I don't see any friction in here, I'll merge it as is. 
@christ66 feel free to submit a new PR with folder level if you have some spare time.

**Comment by warden** [comment]
PR with tests waiting for you @christ66 .
When writing the tests I realized actually that this is not the best solution to disable annotation completely on the site level as this would disable also the "Linking JIRA issues to Run" feature for all builds on this JIRA site.

I'm thinking it would be better to either:
* add option to disable this on a specific Job level
* or introduce a changelog limit (e.g. 20) when parsing the changelog

**Pull request merged**
