### PR TITLE
JENKINS-59001 - IssueSelectorStep should handle NullPointerException caused by having no configured sites

### PR DESCRIPTION
**Pull request by Evildethow**
https://issues.jenkins-ci.org/browse/JENKINS-59001

@olamy are you able to take a look? 

Thanks.

### CODE REVIEW

**Comment by artkoshelev** [comment]
How is it even possible? Fresh install?

**Comment by Evildethow** [comment]
@artkoshelev, in this case, it was triggered by https://issues.jenkins-ci.org/browse/JENKINS-57899

**Comment by artkoshelev** [comment]
I don't think we should fix it here, i'm pretty sure it'll fail somewhere else.

**Comment by olamy** [comment]
even if fixing the root cause is more important. it's still good to be NPE free

**Pull request merged**
