### PR TITLE
[JENKINS-60113] Use Object as data type to fieldValue

### PR DESCRIPTION
**Pull request by jcwoos**
Label custom fields expect an array of strings as value

### CODE REVIEW

**Comment by warden** [comment]
@jcwoos can you make sure this is working with the previous configuration (i.e. that the configuration is handled properly if it was saved in the previous format?)
Easiest way to do this is by configuring the JIRA site without this change, then update the plugin to the SNAPSHOT version you changed and verify you can edit the setting and update it without any exception.

**Comment by jcwoos** [comment]
I tested with label, text and datetime fields. all of them updated normally.
// label field
step([$class: 'hudson.plugins.jira.pipeline.IssueFieldUpdateStep',
                     issueSelector: [$class: 'hudson.plugins.jira.selector.DefaultIssueSelector'],
                     fieldId: '12606',
                     fieldValue: ["test-${env.BUILD_NUMBER}"]]);
// text field
step([$class: 'hudson.plugins.jira.pipeline.IssueFieldUpdateStep',
                     issueSelector: [$class: 'hudson.plugins.jira.selector.DefaultIssueSelector'],
                     fieldId: '12608',
                     fieldValue: "test-${env.BUILD_NUMBER}"]);
// date field
step([$class: 'hudson.plugins.jira.pipeline.IssueFieldUpdateStep',
                     issueSelector: [$class: 'hudson.plugins.jira.selector.DefaultIssueSelector'],
                     fieldId: '12607',
                     fieldValue: "20191114T150913.195-0300"]);

**Comment by artkoshelev** [comment]
Could you pls add tests to document the change?

**Comment by jcwoos** [comment]
Sorry about the identation, my eclipse do auto-format and organize imports before save..

**Comment by warden** [comment]
@jcwoos sorry for taking a look at this so late, any chance you could rebase this?
Also I see your comment in (JENKINS-60113)[https://issues.jenkins-ci.org/browse/JENKINS-60113] - does it mean that you actually didn't need those changes?

**Comment by jcwoos** [comment]
Hello @warden, no problem.
I did the rebase as requested.
That comment was made when I was trying to fix this problem. Was an enviroment issue.

**Comment by warden** [comment]
@jcwoos seems like the rebase didn't work as expected, check the commits and files changes tabs of the PR - you should have there only your commits. 

If you have problems with the rebase, the easiest workaround is to:
- create a new local branch from the current master branch with your changes (commits) only - you can cherry-pick your commits from your current branch
- rename locally the branch that this PR refers to, to some other name so that it doesn't conflict
- rename locally the *new* branch you created to the name that that this PR refers to
- force push the branch to your remote

Let me know in case you need help with this.

**Comment by romanblachman** [comment]
@jcwoos any chance you can rebase so that this can be merged please?

**Comment by romanblachman** [comment]
@warden hello, what's the next step here? anything I can help with?

**Comment by warden** [comment]
@romanblachman as you see this PR needs rebasing and resolving the conflicts, feel free to replace it with another one on the current code, you can easily cherry-pick the one relevant commit/diff from here

**Pull request closed without merging**
