### PR TITLE
Simplify constructor, main URL is the only mandatory field

### PR DESCRIPTION
**Pull request by timja**
Did the review cleanup from: https://github.com/jenkinsci/jira-plugin/pull/173

### CODE REVIEW

**Comment by timja** [comment]
@artkoshelev any chance of a review please?

**Comment by kmcquade** [comment]
@casz - can you please approve so this will be merged? @olamy already approved. We are waiting on this for #168 . Thanks

**Comment by casz** [comment]
I already approved :confused:

**Comment by olamy** [comment]
merged.
@timja or @casz could you please create a Jira so this will be part of the changelog.

**Comment by timja** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-56697

**Pull request merged**
